### ISSUE TITLE
Repo out of sync with Bioc

### ISSUE THREAD

**Issue by lgeistlinger** [bhklab/consensusOV#29]
Hi @gmchen @kofiav, 

Can you please grant me push access to the Github repo?
I would like to initiate syncing the repo with Bioconductor and start to apply the discussed modifications.

Thanks!

**Comment by gangeshberi** [comment]
Hey @lgeistlinger 
 
Just gave you access to consensusOV repository.

**Comment by lgeistlinger** [comment]
Thanks!
